services:
  icemusicmeta:
    image: openjdk:17
    depends_on:
      - icemusicdb
    volumes:
      - ./runapp/service/:/app
    command: bash -c "cd /app && java -jar musicmeta-0.0.1-SNAPSHOT.jar"
    environment:
      DB_SERVER: jdbc:postgresql://icemusicdb:5432/icemusic
    ports:
      - 8585:8585
  icemusicdb:
    image: postgres:15.4-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: icemusic
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 15430:5432
networks:
  default:
    name: icenetworks
